### ISSUE TITLE
希望能增加关闭激活和初次执行all脚本

### ISSUE THREAD

**Issue by imoldchen** [pbbqdd/btjh#2]
感谢大佬写的App，虽然简陋但是很适合我这种懒癌患者，希望能增加两个功能：
1.增加关闭按钮，执行两个命令：
killall com.zuoyou.inject
killall knife_server
2.增加一个初始化按钮，执行 all 脚本的内容，这样不用每次更新都去敲一遍命令。

左游游戏厅app是把激活程序和脚本内置 assets\inject 目录下，并安装到 /storage/emulated/0/zuoyou 目录，按道理说，是可以实现的，只是不知道大佬有没有时间做一下。

**Comment by pbbqdd** [comment]
太懒了，暂时没有这方面更新计划 @imoldchen
